### ISSUE TITLE
404 produces a stack trace

### ISSUE THREAD

**Issue by anewton1998** [arineng/nicinfo#29]
```
andy@ubuntu:~/projects/nicinfo$ bundle exec bin/nicinfo -V --pager no arin-o
# NicInfo v.1.3.0-alpha1
## Using configuration found in /home/andy/.NicInfo
# Your configuration is old. Use --reset to create a new one.
## Evicted 0 files from the cache
## Assuming query value is ENTITYHANDLE
## Looking up bootstrap from /home/andy/.NicInfo/bsfiles/entity.json
## Issuing GET for https://rdap.arin.net/registry/entity/arin-o
# Query yielded no results.
## Server conforms to rdap_level_0

[ NOTICE ] Terms of Service
         1 By using the ARIN RDAP/Whois service, you are agreeing to the RDAP/Whois Terms of Use
     About https://www.arin.net/whois_tou.html

 [ ERROR ] ENTITY NOT FOUND
      Code 404
         1 The entity you are seeking as 'ARIN-O' is/are not here.

## Server response code was 404
bundler: failed to load command: bin/nicinfo (bin/nicinfo)
NoMethodError: undefined method `[]' for true:TrueClass
  /home/andy/projects/nicinfo/lib/nicinfo/notices.rb:45:in `display_notices'
  /home/andy/projects/nicinfo/lib/nicinfo/nicinfo_main.rb:630:in `display_rdap_query'
  /home/andy/projects/nicinfo/lib/nicinfo/nicinfo_main.rb:509:in `run'
  bin/nicinfo:25:in `<top (required)>'
```

**Comment by anewton1998** [comment]
fixed in 1.2.2
