### ISSUE TITLE
using base url on command line causes problems

### ISSUE THREAD

**Issue by anewton1998** [arineng/nicinfo#36]
~~~
andy@ubuntu:~/projects/nicinfo$ bundle exec bin/nicinfo -V -b http://rdap.arin.net/bootstrap 192.136.136.2
# NicInfo v.1.5.0-alpha1
## Using configuration found in /home/andy/.NicInfo
## Evicted 0 files from the cache
## Assuming query value is IP4ADDR
bundler: failed to load command: bin/nicinfo (bin/nicinfo)
NoMethodError: undefined method `end_with?' for nil:NilClass
  /home/andy/projects/nicinfo/lib/nicinfo/rdap_query.rb:224:in `make_rdap_url'
  /home/andy/projects/nicinfo/lib/nicinfo/rdap_query.rb:80:in `do_rdap_query'
  /home/andy/projects/nicinfo/lib/nicinfo/nicinfo_main.rb:504:in `run'
  bin/nicinfo:25:in `<top (required)>'

~~~

**Comment by gdubin** [comment]
This bug appears to be OBE on master.  A new release is coming in the next few weeks so closing for now.

Thank you for your feedback.
