### ISSUE TITLE
"in `process': undefined method `size' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by bortzmeyer** [arineng/nicinfo#40]
It seems nicinfo chokes on some RDAP servers (reading the JSON output of this server, `rdap.nic.bostik`, shows no obvious issue).

```
% nicinfo nic.bostik
# NicInfo v.1.4.1
# Result type is DOMAIN.
/var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/entity.rb:134:in `process': undefined method `size' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/entity.rb:255:in `process'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/common_json.rb:71:in `block in process_entities'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/common_json.rb:69:in `each'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/common_json.rb:69:in `process_entities'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/domain.rb:112:in `process'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/domain.rb:35:in `block in display_domain'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/domain.rb:34:in `each'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/domain.rb:34:in `display_domain'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/nicinfo_main.rb:701:in `display_rdap_query'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/lib/nicinfo/nicinfo_main.rb:537:in `run'
	from /var/lib/gems/2.5.0/gems/nicinfo-1.4.1/bin/nicinfo:25:in `<top (required)>'
	from /local/bin/nicinfo:23:in `load'
	from /local/bin/nicinfo:23:in `<main>'
```

**Comment by bortzmeyer** [comment]
I note that this RDAP server returns no rdapConformance, no notices and no remarks. It seems to me (RFC 7483) that these JSON members are not mandatory and therefore nicinfo should not crash.

**Comment by gdubin** [comment]
This has been fixed on master and should be included in the next release (coming in a few weeks).  We're no longer stacking when the input does not conform to the standard, instead we'll display a warning.

One quick note: the rdapConformance field is a MUST per the latest draft of 4783.  I'm not sure if that's changed since your last viewing.

Thanks for the feedback!
